# Generated by Django 6.0.3 on 2026-03-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
